const STORAGE_KEY='usp-cooling-tower-walkdown-v1';
const sections=[
{title:'1. Existing Cooling Tower & Drive',questions:[
['What is the cooling tower manufacturer, model, serial number, and fan configuration?','Photograph every tower/nameplate and confirm how many fans are actually involved.',true],
['What are the existing fan motor nameplate details?','Capture HP, voltage, phase, FLA, RPM, frame, service factor, enclosure, and manufacturer.',true],
['What are the existing VFD make, model, horsepower/current ratings, input voltage, and enclosure?','Get clear nameplate and interior photos if safely accessible.',true],
['Is the current motor/VFD intended to remain as Motor/VFD A with one new redundant Motor/VFD B, or are both sets to be replaced?','',true],
['How is the existing motor mechanically connected to the fan today?','Direct shaft, coupling, belt, gearbox, jackshaft, etc.',true],
['What is the current VFD control method and speed reference?','PLC/network, 4–20 mA, potentiometer, PID, fixed speed, temperature control, etc.',false],
['Are there existing drawings, manuals, VFD parameter backups, or cooling-tower OEM documents we can receive?','',false]]},
{title:'2. Mechanical Redundancy / Clutch System',questions:[
['Who is expected to engineer and furnish the dual-motor mechanical/clutch arrangement?','Confirm whether US Pipe has an OEM/mechanical vendor or expects the bidding team to provide this package.',true],
['Does US Pipe already have a preferred clutch design, manufacturer, or example system in mind?','',true],
['How will each clutch be actuated?','Electric, pneumatic, hydraulic, or other. Identify utilities available nearby.',true],
['How is clutch ENGAGED and DISENGAGED status expected to be proven?','Limit switch, prox, integral switch, pressure switch, etc.',true],
['How many actual fan shafts/fans require zero-speed detection?','The scope references zero-speed switches for each fan; verify the actual physical arrangement.',true],
['Where can the second motor, clutch hardware, supports, and guards physically fit while keeping both motors outside the tower?','Measure usable footprint, elevations, access, obstructions, and service clearances.',true],
['Will structural steel, platforms, guarding, shafting, couplings, alignment, and mechanical installation be part of the bidder’s turnkey scope?','',true],
['Who will install the inlet and outlet RTD thermowells and perform any piping/welding work?','Confirm piping material, welding requirements, and who owns the mechanical shutdown.',false]]},
{title:'3. Transfer Sequence & Operating Philosophy',questions:[
['Is motor/VFD selection intended to be MANUAL at the double-throw disconnect, or should the system automatically fail over between A and B?','The scope says automated redundancy but also starts the sequence with selection at a double-throw disconnect.',true],
['Exactly what device is the “double-throw disconnect,” and what is it switching?','Confirm whether it is power-side transfer equipment, a manual selector/control device, or something else. Get an intended one-line if available.',true],
['If Motor/VFD A faults while running, what should happen?','Alarm only, stop and wait for operator, automatic transfer to B, or another sequence.',true],
['What conditions should initiate or permit a transfer?','VFD fault, motor overload, loss of rotation, temperature, manual command, maintenance selection, etc.',false],
['Must the fan be proven completely stopped before either clutch can change state?','Confirm zero-speed permissive and any required coast-down delay.',true],
['What should happen if a clutch command does not match its feedback?','Timeout, alarm, inhibit start, transfer attempt, manual intervention, etc.',false],
['Can both clutches ever be engaged at the same time under any maintenance condition?','Establish the required hardwired/software interlocks.',true],
['After a power failure or PLC restart, which drive should be selected and should the system automatically restart?','',false],
['Should the new VFD run with the exact same speed/control profile as the existing VFD?','Confirm acceleration, deceleration, min/max Hz, PID/speed reference, and any special parameters.',false]]},
{title:'4. PLC, Network, HMI & Alarming',questions:[
['Does US Pipe want a new standalone PLC for this project, or integration into an existing PLC?','',true],
['What PLC platform, processor family, firmware/version, and plant programming standards are required?','Confirm Rockwell preference and any required spare/standard part numbers.',true],
['Where will the PLC panel be located?','Measure mounting area and capture environmental conditions / enclosure requirements.',true],
['Where is the plant network connection point and who will provide the IP address / network approval?','Photograph the nearby switch and identify available port/fiber/copper requirements.',true],
['Should the VFDs communicate to the PLC over Ethernet/IP, hardwired I/O, or both?','',false],
['Where are the requested fault alarm bits supposed to be displayed?','Existing HMI, SCADA, DCS, historian, maintenance system, or simply exposed on the plant network.',true],
['Is a local HMI required at the cooling tower?','If yes, confirm desired size, location, functions, and enclosure.',false],
['Do inlet/outlet temperatures, motor status, speed, alarms, and run hours need to be trended or historized?','',false]]},
{title:'5. RTDs, Zero-Speed & Field Instrumentation',questions:[
['What RTD type and plant standard should be used?','Pt100 / 3-wire / transmitter requirements, preferred manufacturer, head style, and signal type.',false],
['Are the inlet/outlet RTDs for indication/alarming only, or will they control fan speed?','',true],
['What are the required normal temperature range, alarm setpoints, and any trip/setback thresholds?','',false],
['Where exactly should the inlet and outlet thermowells be installed?','Capture pipe size, material, insulation, orientation, access, and straight-run limitations.',true],
['What zero-speed switch technology does US Pipe prefer, if any?','Prox with target, shaft-speed sensor, inductive speed monitor, encoder, etc.',false],
['Is any additional feedback required beyond RTDs, clutch state, zero speed, and VFD fault/status?','Motor temperature, vibration, disconnect position, local/remote, HOA, airflow, basin level, etc.',false]]},
{title:'6. Power & Field Electrical',questions:[
['What is the available supply voltage, source, breaker/fuse size, and available fault current?','Capture upstream panel/MCC designation and one-line information.',true],
['Where are the existing VFD, disconnect, and feeder located relative to the cooling tower?','Measure approximate conduit/cable route lengths.',true],
['Is there adequate existing power capacity for the redundant VFD/motor arrangement?','Confirm whether only one drive can run at a time and how feeder sizing is expected to be handled.',true],
['What enclosure/environmental ratings are required for VFDs, PLC panel, disconnects, and field devices?','Indoor/outdoor, NEMA 12/3R/4/4X, washdown/corrosion/heat concerns.',false],
['Are there plant standards for disconnects, breakers, VFDs, conduit, wire, labeling, or instrumentation that are not in the scope document?','',false],
['What existing electrical equipment is to be removed versus reused?','The scope requires abandoned equipment/conduit/cabling to be removed rather than left in place.',true],
['Are any E-stop, safety relay, LOTO, local disconnect, or maintenance-control changes required?','',true]]},
{title:'7. Installation, Responsibilities & Quote',questions:[
['Who is intended to be the prime contractor / single point of contact for the turnkey project?','',true],
['Confirm the expected split between CSI, Sky Electrical, US Pipe, and any mechanical/OEM contractor.','Especially mechanical design/fabrication, piping, conduit/wire, panel work, programming, and commissioning.',true],
['What is the required quote due date?','',true],
['Which shutdown is this targeting and what are the expected shutdown dates?','The scope allows installation/commissioning during the normal winter/summer shutdown window.',true],
['What work can be installed or tested before shutdown without affecting production?','',false],
['What are the expected production-support hours during the required five consecutive days?','Single shift, multiple shifts, weekends, or 24-hour coverage.',true],
['Does the >97% uptime requirement apply to the complete turnkey system, and how will uptime be measured?','',true],
['Can US Pipe provide the separate electrical and mechanical specifications referenced in the scope?','',true],
['Can US Pipe provide all referenced drawings, photographs, existing documentation, and any preferred component standards?','',true],
['Are there site-specific access, lift, scaffold, hot-work, crane, roof, confined-space, or safety requirements that need to be carried in the quote?','',false],
['Are demo, material, and labor the only required proposal breakouts, or does US Pipe want engineering/programming/startup broken out separately as well?','',false]]}
];
const photoItems=['Overall cooling tower from all accessible sides','Cooling tower manufacturer/model/nameplate','Existing motor nameplate and mounting','Existing VFD nameplate, enclosure, and internal wiring','Existing disconnect / feeder / upstream breaker or MCC bucket','Fan shaft, coupling, belt/gearbox, guards, and motor connection','Potential location for second motor / clutch / structural supports','Inlet and outlet piping plus proposed RTD thermowell locations','Existing control panel / PLC / I/O and panel nameplate','Nearest plant network switch and available connection point','Conduit/cable routes and approximate distances','Available wall/floor space for new PLC/VFD/disconnect equipment','Any obstructions, access platforms, ladders, lifts, or crane needs','Existing field sensors, local controls, HOA switches, E-stops, and labels'];
function defaultState(){return{meta:{date:'2026-08-17'},answers:{},skipped:{},photos:{},custom:[]}}
function loadState(){try{return{...defaultState(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return defaultState()}}
let state=loadState(),activeFilter='all';
function saveState(showToast=false){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(showToast)toast('Saved');updateUI()}
function qId(s,q){return`q-${s}-${q}`}
function render(){const host=document.getElementById('sections');host.innerHTML='';let running=1;sections.forEach((section,si)=>{const wrap=document.createElement('section');wrap.className='section';wrap.innerHTML=`<div class="section-head"><h2>${section.title}</h2><div class="section-count" data-count-section="${si}"></div></div><div class="questions"></div>`;const qHost=wrap.querySelector('.questions');section.questions.forEach((q,qi)=>{const[text,hint,critical]=q;qHost.appendChild(makeQuestionCard({id:qId(si,qi),number:running++,text,hint,critical,custom:false}))});host.appendChild(wrap)});if(state.custom.length){const wrap=document.createElement('section');wrap.className='section';wrap.innerHTML='<div class="section-head"><h2>8. Added During Walkthrough</h2><div class="section-count" data-count-custom></div></div><div class="questions"></div>';const qHost=wrap.querySelector('.questions');state.custom.forEach(item=>qHost.appendChild(makeQuestionCard({id:item.id,number:running++,text:item.text,hint:'Custom question',critical:false,custom:true})));host.appendChild(wrap)}const photoHost=document.getElementById('photoGrid');photoHost.innerHTML='';photoItems.forEach((text,i)=>{const id=`photo-${i}`,item=document.createElement('div');item.className='photo-item';item.innerHTML=`<input id="${id}" type="checkbox" ${state.photos[id]?'checked':''}><label for="${id}">${text}</label>`;item.querySelector('input').addEventListener('change',e=>{state.photos[id]=e.target.checked;saveState()});photoHost.appendChild(item)});const notes=document.getElementById('generalNotes');notes.value=state.meta.generalNotes||'';notes.oninput=()=>{state.meta.generalNotes=notes.value;saveState()};updateUI()}
function makeQuestionCard({id,number,text,hint,critical,custom}){const card=document.createElement('article');card.className='q-card';card.dataset.id=id;card.dataset.critical=critical?'true':'false';card.innerHTML=`<div class="q-top"><div class="num">${number}</div><div class="q-text">${esc(text)}${critical?'<span class="critical">CRITICAL</span>':''}</div><label class="skip-wrap"><input type="checkbox" class="skip" ${state.skipped[id]?'checked':''}> Skip / known / N/A</label></div>${hint?`<div class="hint">${esc(hint)}</div>`:''}<textarea class="answer" placeholder="Answer / notes…">${esc(state.answers[id]||'')}</textarea>${custom?'<button class="action danger remove-custom" style="margin-top:9px;padding:6px 9px;font-size:.75rem;">Remove custom question</button>':''}`;card.querySelector('.answer').addEventListener('input',e=>{state.answers[id]=e.target.value;saveState()});card.querySelector('.skip').addEventListener('change',e=>{state.skipped[id]=e.target.checked;saveState()});if(custom)card.querySelector('.remove-custom').addEventListener('click',()=>{state.custom=state.custom.filter(q=>q.id!==id);delete state.answers[id];delete state.skipped[id];saveState();render()});return card}
function allCards(){return[...document.querySelectorAll('.q-card')]}
function cardStatus(card){const id=card.dataset.id;if(state.skipped[id])return'skipped';if((state.answers[id]||'').trim())return'answered';return'open'}
function updateUI(){const cards=allCards();let answered=0,skipped=0,open=0,visible=0;cards.forEach(card=>{const status=cardStatus(card);card.classList.toggle('answered',status==='answered');card.classList.toggle('skipped',status==='skipped');answered+=status==='answered';skipped+=status==='skipped';open+=status==='open';let show=activeFilter==='all'||activeFilter===status;if(activeFilter==='critical')show=card.dataset.critical==='true'&&status==='open';card.classList.toggle('hidden',!show);if(show)visible++});const done=answered+skipped,pct=cards.length?Math.round(done/cards.length*100):0;document.getElementById('progressBar').style.width=`${pct}%`;document.getElementById('progressText').textContent=`${answered} answered · ${skipped} skipped · ${open} open`;document.getElementById('emptyState').style.display=visible?'none':'block';document.querySelectorAll('.section').forEach(section=>{const sc=[...section.querySelectorAll('.q-card')],openCount=sc.filter(c=>cardStatus(c)==='open').length,countEl=section.querySelector('[data-count-section],[data-count-custom]');if(countEl)countEl.textContent=`${openCount} open / ${sc.length}`;section.style.display=sc.some(c=>!c.classList.contains('hidden'))?'':'none'})}
document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{activeFilter=btn.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===btn));updateUI()}));
function addCustomQuestion(){const input=document.getElementById('customQuestion'),text=input.value.trim();if(!text)return;state.custom.push({id:`custom-${Date.now()}`,text});input.value='';saveState();render();toast('Question added')}
document.getElementById('addQuestionBtn').addEventListener('click',addCustomQuestion);document.getElementById('customQuestion').addEventListener('keydown',e=>{if(e.key==='Enter')addCustomQuestion()});
document.getElementById('copyBtn').addEventListener('click',async()=>{const text=buildSummary();try{await navigator.clipboard.writeText(text);toast('Summary copied')}catch{fallbackCopy(text)}});
document.getElementById('exportBtn').addEventListener('click',()=>{const text=buildSummary(),blob=new Blob([text],{type:'text/markdown;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='US-Pipe-Cooling-Tower-Walkdown-2026-08-17.md';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Notes exported')});
document.getElementById('resetBtn').addEventListener('click',()=>{if(!confirm('Clear every answer, skip mark, photo check, and walkthrough note on this device?'))return;localStorage.removeItem(STORAGE_KEY);state=defaultState();render();toast('Walkthrough reset')});
function buildSummary(){const lines=['# US Pipe — Air Compressor Cooling Tower Walkdown','','- **Date:** August 17, 2026'];if(state.meta.generalNotes)lines.push(`- **General notes:** ${state.meta.generalNotes.trim()}`);lines.push('');sections.forEach((section,si)=>{lines.push(`## ${section.title}`,'');section.questions.forEach((q,qi)=>appendQuestion(lines,q[0],qId(si,qi)));lines.push('')});if(state.custom.length){lines.push('## 8. Added During Walkthrough','');state.custom.forEach(q=>appendQuestion(lines,q.text,q.id));lines.push('')}lines.push('## Photo & Measurement Checklist','');photoItems.forEach((text,i)=>lines.push(`- [${state.photos[`photo-${i}`]?'x':' '}] ${text}`));lines.push('','_Generated from the US Pipe Cooling Tower Quote Walkdown page._');return lines.join('\n')}
function appendQuestion(lines,text,id){const status=state.skipped[id]?'SKIPPED / KNOWN / N/A':((state.answers[id]||'').trim()?'ANSWERED':'OPEN');lines.push(`### ${text}`,`**Status:** ${status}`);if((state.answers[id]||'').trim())lines.push('',state.answers[id].trim());lines.push('')}
function fallbackCopy(text){const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();toast('Summary copied')}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>el.classList.remove('show'),1500)}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
render();